project:
  type: website
  output-dir: docs/
website:
  title: "InstrumentQC"
  site-path: "/InstrumentQC_Install/"
  page-navigation: true
  navbar:
    left:
    - text: "Home"
      href: index.qmd
    - text: "Articles"
      menu: 
      - text: "Installing Software"
        href: Installation.qmd
      - text: "Setting up Git and Rstudio"
        href: GitAndRstudio.qmd
      - text: "Installing R packages"
        href: rpackages.qmd
      - text: "Setting File Paths"
        href: filepaths.qmd
      - text: "Dashboard Components"
        href: InstrumentLayout.qmd
      - text: "Automation"
        href: Automation.qmd
    right:
    - icon: github
      href: https://github.com/DavidRach/InstrumentQC_Install
      aria-label: GitHub
  page-footer:
    background: light
    right: Built with [Quarto](https://quarto.org/){target=_blank}

format:
  html:
    theme: styles.scss