---
toc: true
---
Still Working On This Section, sorry! - David

# Conclusion

Congratulations, you have reached the end of this brief walkthrough of how we created our website/dashboards. We hope this has been helful and wish you success on your own modifications and tinkering. 

Below are a miscellaneous collection of advanced topics and future directions that are not essential, but we have been working on integrating into our website, and some may want to incorporate as well. 

Best-
David

# Future Directions - Github Actions

Rendering locally takes computer time and computer space. Additionally, it means each instrument needs to bring in edited versions of the website locally every morning with their initial pull. We are currently working to set up a GitHub actions that would ensure the website portion remains only within the GitHub repository (not rendered or copied locally to each instrument taking up additional memory) but additionally render at a given time reducing the requirement to manually render and push the updated dashboard. This occurs thanks to cloud access available to GitHub repositories that are public, with a certain ammount of free server time allocated to each. 

The reason not currently available, is that it is more complicated technically and I am busy writing. But more broadly, the cloud instance needs to install R and R packages needed to run everything each and every time. And the Luciernaga package is still MB heavy due to it being in testing phase and having a lot of .fcs files in it's extdata folder. Consequently, an area that has promise, but not yet implemented, stay tuned. For now, we have set an additional taskschedule that runs on a local computer at 11 AM, triggers quarto render, and passes the resulting website to GitHub. 

