# InstrumentQC 

Having reached this webpage, you have likely discovered the [InstrumentQC dashboard](https://umgccfcss.github.io/InstrumentQC/) dashboard I implemented at the University of Maryland, Baltimore for our four Cytek Aurora instruments. This website is for those who would like to understand how it is implemented, either for curiosity or because you'd like to modify the code to visualize the instrument QC data for your own Cytek instruments at your current workplace.  

Having placed significant effort into this pet-project, I would love for others in the cytometry community to benefit from it. Setting it up from scratch requires some familiarity with both R and Git, so to give the average cytometry aficionado a fighting-chance I am providing this detailed explanation of the process of setting up and customizing the dashboard. 

If you get stuck, or parts of the documentation are unclear, please reach out by opening an [issue](https://github.com/DavidRach/InstrumentQC_Install/issues) and I will try my best to help you troubleshoot. what makes free-and-open source software great (and fun to work with in my opinion) is seeing how the collective small contributions of users improve the project over time. 

Best-
David

# Overview

After daily QC is run on a Cytek instrument, the relevant information is stored as .fcs and .csv files in specific folders. Using functions incorporated in the [Luciernaga](https://github.com/DavidRach/Luciernaga) R package, the data associated with these newly generated files is processed using [R](https://www.r-project.org/) once a day at a user-designated time (implemented via Windows Task Sceduler). The version control software [Git](https://git-scm.com/) keeps track of changes to the processed data, passing updates to the online [GitHub](https://github.com/) repository for storage. This data is then referenced when building the dashboard website using [Quarto](https://quarto.org/), which is published as a GitHub page allowing for url access.

For multiple instruments, the above process is repeated on each instruments computer, and the Quarto webpages are modified to display data from each instrument. 